# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-release
cache: packages
r_packages:
  - covr
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
